export const GAME_CONFIG = {
	TOTAL_CARDS: 52,
	MAX_PLAYERS: 4,
	MIN_PLAYERS: 2,
	CARDS_PER_PLAYER: 3,
	ELIMINATION_POINTS: 50,
	LOW_CARD_THRESHOLD: 3,
	STOP_SUM_LOW: 6,
	STOP_SUM_MEDIUM: 10,
} as const
